import{a as E,S as q,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const P="https://pixabay.com/api/",R="52398872-c12541878b4eb59882334d5d5",B=15;async function p(n,r=1){try{return(await E.get(P,{params:{key:R,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:B}})).data}catch(t){throw new Error(t)}}const h=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-more");let M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(n){const r=n.map(({webformatURL:t,largeImageURL:i,tags:e,likes:o,views:s,comments:S,downloads:v})=>`
        <li class="gallery-item">
          <a href="${i}" class="gallery-link">
            <img src="${t}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${o}</p>
            <p><b>Views:</b> ${s}</p>
            <p><b>Comments:</b> ${S}</p>
            <p><b>Downloads:</b> ${v}</p>
          </div>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",r),M.refresh()}function $(){h.innerHTML=""}function y(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function b(){f.classList.remove("hidden")}function l(){f.classList.add("hidden")}const w=document.querySelector(".form"),O=w.querySelector("input[name='search-text']");let d="",c=1,u=0;w.addEventListener("submit",x);f.addEventListener("click",A);async function x(n){n.preventDefault();const r=O.value.trim();if(!r){a.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}d=r,c=1,$(),l(),y();try{const t=await p(d,c);if(u=t.totalHits,t.hits.length===0){a.info({title:"No results",message:"No images found.",position:"topRight"});return}g(t.hits),u>t.hits.length&&b()}catch{a.error({title:"Error",message:"Something went wrong.",position:"topRight"})}finally{L()}}async function A(){c+=1,y(),l();try{const n=await p(d,c);g(n.hits),c*15>=u?(l(),a.info({title:"End of results",message:"You've reached the end.",position:"topRight"})):b();const t=document.querySelector(".gallery-item");if(t){const{height:i}=t.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}}catch{a.error({title:"Error",message:"Something went wrong.",position:"topRight"})}finally{L()}}
//# sourceMappingURL=index.js.map
