import{a as S,S as q,i as s}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const P="https://pixabay.com/api/",R="52398872-c12541878b4eb59882334d5d5",B=15;async function p(n,o=1){try{return(await S.get(P,{params:{key:R,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:B}})).data}catch(t){throw new Error(t)}}const h=document.querySelector(".gallery"),m=document.querySelector(".loader"),a=document.createElement("button");a.textContent="Load more";a.classList.add("load-more","hidden");h.insertAdjacentElement("afterend",a);let M=new q(".gallery a",{captionsData:"alt",captionDelay:250});function g(n){const o=n.map(({webformatURL:t,largeImageURL:i,tags:e,likes:r,views:l,comments:E,downloads:v})=>`
        <li class="gallery-item">
          <a href="${i}" class="gallery-link">
            <img src="${t}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${r}</p>
            <p><b>Views:</b> ${l}</p>
            <p><b>Comments:</b> ${E}</p>
            <p><b>Downloads:</b> ${v}</p>
          </div>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",o),M.refresh()}function $(){h.innerHTML=""}function y(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function b(){a.classList.remove("hidden")}function d(){a.classList.add("hidden")}const w=document.querySelector(".form"),x=w.querySelector("input[name='search-text']");let u="",c=1,f=0;w.addEventListener("submit",A);a.addEventListener("click",O);async function A(n){n.preventDefault();const o=x.value.trim();if(!o){s.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}u=o,c=1,$(),d(),y();try{const t=await p(u,c);if(f=t.totalHits,t.hits.length===0){s.info({title:"No results",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}g(t.hits),f>t.hits.length?b():(d(),s.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{s.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{L()}}async function O(){c+=1,y(),d();try{const n=await p(u,c);g(n.hits),c*15>=f?(d(),s.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b();const t=document.querySelector(".gallery-item");if(t){const{height:i}=t.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}}catch{s.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{L()}}
//# sourceMappingURL=index.js.map
